version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ~/docker/postgres/mount:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: django
      POSTGRES_DB: rental
      PGDATA: /var/lib/postgresql/data/pgdata 